test_that("mrp_view_* are identicals", {
  expect_identical(mrp_view('eez'), mrp_view_eez())
  expect_identical(mrp_view('eez_boundaries'), mrp_view_eez_boundaries())
  expect_identical(mrp_view('eez_12nm'), mrp_view_eez_12nm())
  expect_identical(mrp_view('eez_24nm'), mrp_view_eez_24nm())
  expect_identical(mrp_view('eez_internal_waters'), mrp_view_eez_internal_waters())
  expect_identical(mrp_view('high_seas'), mrp_view_high_seas())
  expect_identical(mrp_view('ecs'), mrp_view_ecs())
  expect_identical(mrp_view('ecs_boundaries'), mrp_view_ecs_boundaries())
  expect_identical(mrp_view('iho'), mrp_view_iho())
  expect_identical(mrp_view('goas'), mrp_view_goas())
  expect_identical(mrp_view('eez_iho'), mrp_view_eez_iho())
  expect_identical(mrp_view('eez_land'), mrp_view_eez_land())
  expect_identical(mrp_view('longhurst'), mrp_view_longhurst())
  expect_identical(mrp_view('cds'), mrp_view_cds())
  expect_identical(mrp_view('eca_reg13_nox'), mrp_view_eca_reg13_nox())
  expect_identical(mrp_view('eca_reg14_sox_pm'), mrp_view_eca_reg14_sox_pm())
  expect_identical(mrp_view('worldheritagemarineprogramme'), mrp_view_worldheritagemarineprogramme())
  expect_identical(mrp_view('lme'), mrp_view_lme())
  expect_identical(mrp_view('ecoregions'), mrp_view_ecoregions())
  expect_identical(mrp_view('seavox_v18'), mrp_view_seavox_v18())
})

