structure(list(url = "https://geo.vliz.be/geoserver/wfs?service=WFS&version=2.0.0&typeNames=MarineRegions:ecs_boundaries&cql_filter=this%20is%20not%20a%20good%20filter&request=GetFeature", 
    status_code = 400L, headers = structure(list(`access-control-allow-origin` = "*", 
        `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
        `content-type` = "application/xml", `transfer-encoding` = "chunked", 
        date = "Fri, 27 Jan 2023 15:07:57 GMT"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(`access-control-allow-origin` = "*", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `content-type` = "application/xml", `transfer-encoding` = "chunked", 
            date = "Fri, 27 Jan 2023 15:07:57 GMT"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\"?><ows:ExceptionReport xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:ows=\"http://www.opengis.net/ows/1.1\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"2.0.0\" xsi:schemaLocation=\"http://www.opengis.net/ows/1.1 https://geo.vliz.be/geoserver/schemas/ows/1.1.0/owsAll.xsd\">\n<ows:Exception exceptionCode=\"NoApplicableCode\">\n<ows:ExceptionText>Could not parse CQL filter list.\nEncountered &amp;quot;is not a&amp;quot; at line 1, column 6.\nWas expecting one of:\n    &amp;quot;(&amp;quot; ...\n    &amp;quot;:&amp;quot; ...\n    &amp;lt;IDENTIFIER&amp;gt; ...\n    &amp;quot;.&amp;quot; ...\n    &amp;lt;NOT&amp;gt; ...\n    &amp;quot;in&amp;quot; ...\n    &amp;quot;tequals&amp;quot; ...\n    &amp;quot;before&amp;quot; ...\n    &amp;quot;after&amp;quot; ...\n    &amp;quot;during&amp;quot; ...\n    &amp;quot;*&amp;quot; ...\n    &amp;quot;/&amp;quot; ...\n    &amp;quot;+&amp;quot; ...\n    &amp;quot;-&amp;quot; ...\n    &amp;quot;like&amp;quot; ...\n    &amp;quot;ilike&amp;quot; ...\n    &amp;quot;exists&amp;quot; ...\n    &amp;quot;does-not-exist&amp;quot; ...\n    &amp;quot;is&amp;quot; &amp;quot;null&amp;quot; ...\n    &amp;quot;is&amp;quot; &amp;lt;NOT&amp;gt; &amp;quot;null&amp;quot; ...\n    &amp;quot;between&amp;quot; ...\n    &amp;lt;EQ&amp;gt; ...\n    &amp;lt;GT&amp;gt; ...\n    &amp;lt;LT&amp;gt; ...\n    &amp;lt;GTE&amp;gt; ...\n    &amp;lt;LTE&amp;gt; ...\n    &amp;lt;NEQ&amp;gt; ...\n     Parsing : this is not a good filter.</ows:ExceptionText>\n</ows:Exception>\n</ows:ExceptionReport>\n"), 
    date = structure(1674832077, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 7.7e-05, 
    connect = 7.8e-05, pretransfer = 0.00014, starttransfer = 0.006248, 
    total = 0.01353)), class = "response")
